[OPENAI]
api_key = "<your_api_key_here>"
model = "gpt-3.5-turbo"
# Default parameters for the OpenAI API
# temperature=1.0
# top_p=1.0
# frequency_penalty=0.0
# presence_penalty=0.0

[CLAUDE]
api_key = "<your_api_key_here>"
# model = "claude-3-5-haiku-latest"

[GEMINI]
api_key = "<your_api_key_here>"
# model = "