import streamlit as st
import os
import genai_docgen.src.clients.genai_client as genai_client
import genai_docgen.src.utils.docgen as docgen
import configparser
import io
from streamlit_sortables import sort_items
import importlib

# --- Load prompts from prompts.py ---
import prompts

def load_prompts():
    # Reload to get latest if file changed
    importlib.reload(prompts)
    return prompts.PROMPTS.copy() if hasattr(prompts, "PROMPTS") else []

def save_prompts(prompts_list):
    # Overwrite prompts.py with the new PROMPTS list
    with open("src/prompts.py", "w") as f:
        f.write("# This file is auto-generated by the web interface.\n")
        f.write("PROMPTS = [\n")
        for p in prompts_list:
            # Escape quotes and backslashes
            safe_p = p.replace("\\", "\\\\").replace("\"", "\\\"")
            f.write(f'    "{safe_p}",\n')
        f.write("]\n")

st.title("GenAI DocGen Web Interface")

# --- INI File Upload and Edit ---
st.subheader("Upload and Edit ai.ini")
ini_file = st.file_uploader("Upload ai.ini", type=["ini"])
ini_config = configparser.ConfigParser()
ini_text = ""

if ini_file is not None:
    ini_text = ini_file.getvalue().decode()
    ini_config.read_string(ini_text)
    st.success("INI file loaded.")

    # Let user select section to edit
    sections = ini_config.sections()
    if sections:
        section = st.selectbox("Select section to edit", sections)
        # Show current API key and allow editing
        api_key = st.text_input("API Key", value=ini_config.get(section, "api_key", fallback=""))
        if st.button("Update API Key"):
            ini_config.set(section, "api_key", api_key)
            # Save updated ini to a string
            with io.StringIO() as output:
                ini_config.write(output)
                updated_ini = output.getvalue()
            st.download_button("Download updated ai.ini", updated_ini, file_name="ai.ini")
            st.success("API key updated! Download your new ini file.")
    else:
        st.warning("No sections found in ini file.")
else:
    st.info("Upload an ai.ini file to view or edit the API key.")

# --- API Key Input ---
api_key = st.text_input("Enter your API key", type="password")
provider = st.selectbox("Select AI Platform", ["openai", "anthropic", "gemini"])
model = st.text_input("Model", value="gpt-3.5-turbo" if provider == "openai" else "claude-3-5-haiku-latest")

# --- Prompt Editing ---
st.subheader("Prompts (Drag to reorder)")
# Example: initialize prompts
if "prompts" not in st.session_state:
    st.session_state.prompts = [
        "Summarize the corporate website of Acme Corp.",
        "List the main products of Acme Corp."
    ]

sorted_prompts = sort_items(st.session_state.prompts, direction="vertical", key="sortable_prompts")
st.session_state.prompts = sorted_prompts

# Prompt editing UI
for i, prompt in enumerate(st.session_state.prompts):
    cols = st.columns([8, 1])
    st.session_state.prompts[i] = cols[0].text_area(f"Prompt {i+1}", value=prompt, key=f"prompt_{i}")
    if cols[1].button("Remove", key=f"remove_{i}"):
        st.session_state.prompts.pop(i)
        st.experimental_rerun()

if st.button("Add Prompt"):
    st.session_state.prompts.append("")
    st.experimental_rerun()

# --- Output Options ---
output_format = st.selectbox("Output Format", ["docx", "txt", "md", "stdout"])
filename = st.text_input("Output Filename", value="output.docx")

# --- Run Button ---
if st.button("Generate Document"):
    # Set API key in environment for the selected provider
    if provider == "openai":
        os.environ["OPENAI_API_KEY"] = api_key
    elif provider == "anthropic":
        os.environ["ANTHROPIC_API_KEY"] = api_key
    elif provider == "gemini":
        os.environ["GEMINI_API_KEY"] = api_key

    # Get client
    client = genai_client.get_llm_client(provider=provider)
    prompt_response_pairs = []
    for prompt in st.session_state.prompts:
        status = client.get_response(prompt, model=model)
        if status == "Success":
            prompt_response_pairs.append((prompt, client.last_response))
        else:
            st.error(f"Error for prompt: {prompt}\n{status}")
            break

    if prompt_response_pairs:
        docgen.save_responses(
            prompt_response_pairs,
            filename=filename,
            output_format=output_format,
            generate_title=True,
            title="Generated Responses"
        )
        st.success(f"Document generated: {filename}")
        if output_format == "stdout":
            for _, response in prompt_response_pairs:
                st.write(response)
    else:
        st.warning("No responses generated.")

# --- Prompt Editor Section ---
st.subheader("Prompt Editor")
if "prompts" not in st.session_state:
    st.session_state.prompts = load_prompts()

st.subheader("Prompts (Drag to reorder)")
sorted_prompts = sort_items(st.session_state.prompts, direction="vertical", key="sortable_prompts")
st.session_state.prompts = sorted_prompts

# Prompt editing UI
for i, prompt in enumerate(st.session_state.prompts):
    cols = st.columns([8, 1])
    st.session_state.prompts[i] = cols[0].text_area(f"Prompt {i+1}", value=prompt, key=f"prompt_edit_{i}")
    if cols[1].button("Remove", key=f"remove_edit_{i}"):
        st.session_state.prompts.pop(i)
        save_prompts(st.session_state.prompts)
        st.experimental_rerun()

if st.button("Add Prompt"):
    st.session_state.prompts.append("")
    save_prompts(st.session_state.prompts)
    st.experimental_rerun()

if st.button("Save Prompts"):
    save_prompts(st.session_state.prompts)
    st.success("Prompts saved to prompts.py")
